eb-neorv32-ctl: save my changes before syncing

diff --git a/modules/neorv32/tools/eb-neorv32-ctl b/modules/neorv32/tools/eb-neorv32-ctl
--- a/modules/neorv32/tools/eb-neorv32-ctl
+++ b/modules/neorv32/tools/eb-neorv32-ctl
@@ -71,9 +71,6 @@ function f_upload_program() {
         exit 3
       fi
       f_log INFO "[SUCCESS] Neorv32 DPRAM programmed with $v_nrv_program."
-      if [ "$v_nrv_keep_reset" = false ]; then
-        f_start_neorv32
-      fi
       if [ "$v_nrv_examine" == true ]; then
         f_log INFO "Verifying the RAM content against the program file..."
         v_nrv_program_size=$(wc -c < "$v_nrv_program")
@@ -94,7 +91,10 @@ function f_upload_program() {
         else
           f_log INFO "[SUCCESS] Program uploaded and verified."
         fi
-        [ $v_nrv_cmp_status -ne 0 ] && exit 9 
+        [ $v_nrv_cmp_status -ne 0 ] && exit 9
+        if [ "$v_nrv_keep_reset" = false ]; then
+          f_start_neorv32
+        fi
       fi
     else
       f_log ERROR "Can't find file $v_nrv_program!"
@@ -128,6 +128,9 @@ function f_compare_program(){
         f_log INFO "[SUCCESS] The file and RAM content match."
       fi
       [ $v_nrv_cmp_status -ne 0 ] && exit 14
+    else 
+      f_log ERROR "Cannot find file $v_nrv_compare!"
+      exit 15
     fi
   fi
 }
