eb-flash-secure: add checks (again)

diff --git a/tools/eb-flash-secure b/tools/eb-flash-secure
--- a/tools/eb-flash-secure
+++ b/tools/eb-flash-secure
@@ -1,43 +1,46 @@
 #!/bin/bash
-# Get arguments
-device=$1
-gateware=$2
 
 # Plausibility check
-#if (( $# != 2 )); then
-#  echo "Error: Illegal number of parameters ($# given, 2 expected)"
-#  echo "Example usage: $0 dev/wbmX gateware.rpd"
-#  exit 1
-#fi
+if (( $# != 2 )); then
+  echo "Error: Illegal number of parameters ($# given, 2 expected)"
+  echo "Example usage: $0 dev/wbmX gateware.rpd"
+  exit 1
+fi
 
-#device_check='/'$device
-#echo $device_check
-#if [ ! -e "$device_check" ]; then
-#  echo "Error: Device ($device) not found!"
-#  exit 1
-#fi
+# Get arguments
+v_device="$1"
+v_gateware="$2"
 
-#if [ ! -f $gateware ]; then
-#  echo "Error: Gateware ($gateware) not found!"
-#  exit 1
-#fi
+if [ ! -f "$v_gateware" ]; then
+  echo "Error: Gateware '$v_gateware' not found!"
+  exit 1
+fi
+
+# Check if saftbusd is running
+if ps -ax | grep -v grep | grep -q "saftbusd"; then
+  echo "Warning: saftbusd is currently running!"
+fi
 
 # Disable watchdog timer
-eb-reset $device wddisable
-#if [ $? -eq 0 ]; then
-#  echo "Error: Failed to disable the watchdog timer!
-#fi
+eb-reset "$v_device" wddisable
+if [ $? -ne 0 ]; then
+  echo "Error: Failed to disable the watchdog timer!"
+  exit 2
+fi
 
 # Stop all embedded CPUs
-eb-reset $device cpuhalt 0xff
-#if [ $? -eq 0 ]; then
-#  echo "Error: Failed to halt all CPUs!"
-#  exit 1
-#fi
+eb-reset "$v_device" cpuhalt 0xff
+if [ $? -ne 0 ]; then
+  echo "Error: Failed to halt all CPUs!"
+  exit 3
+fi
 
 # Flash device
-eb-flash $device $gateware
-#if [ $? -eq 0 ]; then
-#  echo "Error: Failed to flash the device!"
-#  exit 1
-#fi
+eb-flash "$v_device" "$v_gateware"
+if [ $? -ne 0 ]; then
+  echo "Error: Failed to flash the device!"
+  exit 4
+fi
+
+# Done
+echo "Flash successful! Consider to run eb-reset $v_device fpgareset to restart the FPGA."
